### PR TITLE
xs_watch() triggering on a dead device doesn't mean it's alive again,…

### PR DESCRIPTION
**Pull request by jean-edouard**
… thanks.

Signed-off-by: Jed lejosnej@ainfosec.com

### CODE REVIEW

**Comment by rossphilipson** [comment]
While this seems straight forward and correct, I guess I just worry a bit. It seems really odd what the old code is doing and my worry is that that specific behavior is coupled to some other weird behavior elsewhere. Not sure how best to figure out whether that is a problem.

**Comment by rossphilipson** [comment]
Adding this to the custom build Jed is firing up. If OpenXT starts, runs and stops w/o problems or errors this change should be fine.

**Comment by jean-edouard** [comment]
This is included in this build: http://openxt.ainfosec.com:8020/builders/extbuilder/builds/328
I've tested the build and it (re)boots and starts VMs just fine.

**Comment by rossphilipson** [comment]
Ack. The fix looks good. Will merge soon.

**Pull request merged**
